### ISSUE TITLE
the program will not stop

### ISSUE THREAD

**Issue by YJNDL** [Chengcheng-Xiao/mpiPyMC#2]
<img width="672" alt="1639401900(1)" src="https://user-images.githubusercontent.com/92591977/145820713-453e3779-c463-48e5-b40e-6807cd0e53cf.png">
like this

**Comment by Chengcheng-Xiao** [comment]
Thank you for reporting this. 
This repo hasn't been updated in 3 years (sorry) and some incompatibilities with the current "up-to-date" version of `python` and `mpi4py` are to be expected. I'll update the code in my free time.

In the meantime, may I ask if you are running the examples or your own input when this happened? 

Thx in advance!

**Comment by YJNDL** [comment]
> Thank you for reporting this. This repo hasn't been updated in 3 years (sorry) and some incompatibilities with the current "up-to-date" version of `python` and `mpi4py` are to be expected. I'll update the code in my free time.
> 
> In the meantime, may I ask if you are running the examples or your own input when this happened?
> 
> Thx in advance!

your example

**Comment by Chengcheng-Xiao** [comment]
Should be fixed in 033aa013b659b93d4c1c1378d520cdaed2a4e29c.

**Comment by YJNDL** [comment]
> 

Can you explain the operation in detail?

**Comment by Chengcheng-Xiao** [comment]
The problem was that sending messages using `comm.send` to the same process with `comm.recv` causes the program to hang because these two are blocking operations. I've isolated one process to be the "main" node so that it only collects messages.

If you mean how the whole program work, please check out rajeshrinet's blog: https://rajeshrinet.github.io/blog/2014/ising-model/.

**Comment by Chengcheng-Xiao** [comment]
Closed due to inactivity.
